version: "3"
services:
  jenkins-master:
    build:
      context: .
      dockerfile: ./jenkins
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    container_name: jenkins-master
	