# Configure launched instance for test
- name: Configure instance(s)
  hosts: tstlaunched
  become: True
  remote_user: ubuntu
  gather_facts: True
  tasks:
   - name: update package manager
     apt: update_cache=yes
   - name: Install docker
     apt: name=docker.io state=present
   - name: Install docker-compose
     apt: name=docker-compose update_cache=yes state=present
   - name: Install lynis
     apt: name=lynis state=present
   - name: Install make to build the pythonapp
     apt: name=make state=present     
   - name: Copy the zip file of project
     copy: 
       src: pythonapp.tar.gz 
       dest: /home/ubuntu/pythonapp.tar.gz
   - name: Unzip it
     unarchive: 
       src: /home/ubuntu/pythonapp.tar.gz
       dest: /home/ubuntu/
       copy: no
   - name: Run the application with docker
     shell: make install
     async: 45
     poll: 0
# run the web server as async task, and poll 0 means ansible will fire and forget
