---
# Create ec2 instance and add it to ansible inventory
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: homekeypair
    instance_type: t2.micro
    security_group: launch-wizard-5
    image: ami-0be057a22c63962cb
    region: eu-west-2
    tagname: Name=TestServer

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-02a17e56e6827124a
         assign_public_ip: yes
         instance_tags: "{tagname}}"
      register: ec2
      #register the details of instance to ec2 object for use later

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        #add the ip address to launched group in the hosts file so we can reference it later
        groupname: tstlaunched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"

# Configure launched instance for test
- name: Configure instance(s)
  hosts: tstlaunched
  become: True
  remote_user: ubuntu
  gather_facts: True
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'
  tasks:
   - name: update package manager
     apt: update_cache=yes
   - name: Install docker
     apt: name=docker.io state=present
   - name: Install docker-compose
     apt: name=docker-compose state=present
   - name: Install lynis
     apt: name=lynis state=present
   - name: Copy the zip file of project
     copy: 
       src: binary.zip 
       dest: /home/ubuntu/binary.zip
   - name: Unzip it
     unarchive: 
       src: /home/ubuntu/binary.zip
       dest: /home/ubuntu/
       copy: no
   - name: Run the application with docker
       shell: make install
       args:
        chdir: gossip-world/
