---
# Create ec2 instance and add it to ansible inventory
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: homekeypair
    instance_type: t2.micro
    security_group: launch-wizard-5
    image: ami-0be057a22c63962cb
    region: eu-west-2
    tagname: Name=TestServer

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-02a17e56e6827124a
         assign_public_ip: yes
         instance_tags: "{{tagname}}"
      register: ec2
      #register the details of instance to ec2 object for use later

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        #add the ip address to launched group in the hosts file so we can reference it later
        groupname: tstlaunched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"
